use std::path::PathBuf;

use clap::{Args, Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(
    name = "nf-source",
    about = "Video source pipeline for NextFrame",
    long_about = "Video source pipeline for NextFrame.\n\n\
        Full pipeline: download → transcribe/align → cut → preview.\n\
        All cut operations address content by sentence ids, not timestamps.",
    after_long_help = "\
        DECISION: TRANSCRIBE vs ALIGN\n\n  \
        Have an SRT subtitle file? → nf-source align (whisperX, ~20ms precision)\n  \
        No subtitles?              → nf-source transcribe (Whisper ASR, ~200ms precision)\n  \
        Both produce identical sentences.json.\n\n\
        FULL PIPELINE:\n\n  \
        nf-source download --url <URL> --out-dir project/\n  \
        nf-source transcribe --video project/source.mp4 --out-dir project/\n  \
        nf-source cut --video project/source.mp4 --sentences-path project/ \\\n    \
          --plan-path plan.json --out-dir project/clips/\n  \
        nf-source preview --sentences-path project/ \\\n    \
          --cut-report-path project/clips/cut_report.json --out-path project/preview/"
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Download a video with yt-dlp. Outputs: source.mp4, meta.json.
    Download(DownloadArgs),
    /// Transcribe video to word-level sentences.json via Whisper.
    Transcribe(TranscribeArgs),
    /// Force-align SRT subtitles against audio via whisperX.
    Align(AlignArgs),
    /// Cut clips by sentence-id plan. Outputs: clip_XX.mp4, cut_report.json.
    Cut(CutArgs),
    /// Generate HTML preview page with karaoke highlighting.
    Preview(PreviewArgs),
}

#[derive(Debug, Args)]
pub struct DownloadArgs {
    #[arg(long)]
    pub url: String,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value_t = 1080)]
    pub format_height: u16,
}

#[derive(Debug, Args)]
pub struct TranscribeArgs {
    #[arg(long)]
    pub video: PathBuf,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value = "large-v3")]
    pub model: String,
    #[arg(long, default_value = "en")]
    pub language: String,
    #[arg(long, default_value_t = 1)]
    pub jobs: usize,
}

#[derive(Debug, Args)]
pub struct AlignArgs {
    #[arg(long)]
    pub video: PathBuf,
    #[arg(long)]
    pub srt_path: PathBuf,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value = "auto")]
    pub language: String,
}

#[derive(Debug, Args)]
pub struct CutArgs {
    #[arg(long)]
    pub video: PathBuf,
    #[arg(long)]
    pub sentences_path: PathBuf,
    #[arg(long)]
    pub plan_path: PathBuf,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value_t = 0.0)]
    pub margin_sec: f64,
}

#[derive(Debug, Args)]
pub struct PreviewArgs {
    #[arg(long)]
    pub sentences_path: PathBuf,
    #[arg(long)]
    pub cut_report_path: PathBuf,
    #[arg(long)]
    pub out_path: PathBuf,
    #[arg(long, default_value = "NextFrame Source Preview")]
    pub title: String,
    #[arg(long, default_value = "Generated by nf-source preview")]
    pub subtitle: String,
    #[arg(long, default_value = "#f97316")]
    pub accent: String,
    #[arg(long, default_value = "sunrise")]
    pub theme: String,
}
