import countUp from "../behaviors/data/countUp.js";
import barGrow from "../behaviors/data/barGrow.js";
import lineDraw from "../behaviors/data/lineDraw.js";
import nodeReveal from "../behaviors/data/nodeReveal.js";
import mapPin from "../behaviors/data/mapPin.js";
import pieFill from "../behaviors/data/pieFill.js";
import chartReveal from "../behaviors/data/chartReveal.js";
import fadeIn from "../behaviors/entrance/fadeIn.js";
import slideInUp from "../behaviors/entrance/slideInUp.js";
import popIn from "../behaviors/entrance/popIn.js";

const meta = { name: "sharedData", kind: "scene-helper", description: "Shared nf-anim data-scene builders" };
const FONT = "Avenir Next, Helvetica Neue, sans-serif";
const WARM = { bg: "#1b1512", panel: "#2a201b", card: "#342822", line: "#5c4a3f", text: "#f5ece1", muted: "#d2b9a2", accent: "#da7756", gold: "#f0b172", clay: "#8f5f48", sand: "#f7d6a2" };
const LANDS = [[[-420, -70], [-320, -120], [-250, -80], [-220, -10], [-260, 50], [-360, 40], [-420, -10]], [[-250, 70], [-180, 140], [-210, 250], [-260, 200], [-280, 120]], [[0, -120], [80, -150], [140, -90], [110, -20], [30, -10], [-10, -60]], [[0, 20], [80, 10], [120, 90], [70, 190], [0, 170], [-30, 90]], [[150, -100], [310, -130], [440, -70], [400, 20], [260, 40], [170, 10]], [[340, 150], [430, 170], [460, 230], [390, 270], [320, 220]]];
const PIN_MAP = { na: [0.24, 0.33], sa: [0.31, 0.69], eu: [0.49, 0.27], africa: [0.5, 0.53], asia: [0.69, 0.38], oceania: [0.82, 0.72], us: [0.22, 0.33], uk: [0.46, 0.24], india: [0.64, 0.47], japan: [0.78, 0.34], singapore: [0.7, 0.58] };
const n = (v, d = 0) => Number.isFinite(Number(v)) ? Number(v) : d;
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const clone = (v) => JSON.parse(JSON.stringify(v));
const vpOf = (vp = {}) => [Math.max(360, n(vp.width, 1280)), Math.max(240, n(vp.height, 720)), Math.min(Math.max(360, n(vp.width, 1280)), Math.max(240, n(vp.height, 720)))];
const txt = (x, y, text, fontSize, fill = WARM.text, extra = {}) => ({ shape: "text", at: [x, y], text: String(text), fontSize, fill, font: FONT, ...extra });
const box = (x, y, width, height, fill = WARM.panel, extra = {}) => ({ shape: "rect", at: [x, y], width, height, radius: Math.min(width, height) * 0.1, fill, ...extra });
const base = (W, H) => [{ shape: "rect", at: [W / 2, H / 2], width: W, height: H, fill: WARM.bg }, { shape: "rect", at: [W / 2, H * 0.1], width: W * 0.82, height: Math.max(2, H * 0.004), fill: WARM.line, opacity: 0.35 }];
const dataOf = (data, fallback) => Array.isArray(data) && data.length ? data : data && typeof data === "object" ? Array.isArray(data.items) && data.items.length ? data.items : [data] : fallback;
const itemOf = (item, i, fallback = 0) => typeof item === "number" ? { label: `Metric ${i + 1}`, value: item, suffix: "" } : { label: item?.label || item?.name || item?.title || `Metric ${i + 1}`, value: n(item?.value ?? item?.amount ?? item?.percent ?? item?.score, fallback), suffix: item?.suffix || item?.unit || "" };
const chartOf = (data, fallback) => dataOf(data, fallback).map((item, i) => itemOf(item, i, fallback[i]?.value || 0));
const compareOf = (data, fallback) => dataOf(data, fallback).map((item, i) => typeof item === "number" ? { label: `Metric ${i + 1}`, left: item, right: item * 0.8 } : { label: item?.label || `Metric ${i + 1}`, left: n(item?.left ?? item?.a ?? item?.before ?? item?.value, 0), right: n(item?.right ?? item?.b ?? item?.after ?? item?.target, 0) });
const pinOf = (item, i) => { const key = String(item?.region || item?.code || item?.label || "").toLowerCase().replace(/\s+/g, ""); const xy = Number.isFinite(Number(item?.x)) && Number.isFinite(Number(item?.y)) ? [n(item.x), n(item.y)] : PIN_MAP[key] || [[0.24, 0.33], [0.48, 0.28], [0.68, 0.42], [0.82, 0.7]][i % 4]; return { label: item?.label || item?.name || `Point ${i + 1}`, value: n(item?.value ?? item?.amount ?? 50, 50), x: clamp(xy[0], 0.08, 0.92), y: clamp(xy[1], 0.12, 0.88) }; };
const withScene = (metaIn, sample, build) => ({ ...metaIn, render(host, t, params = {}, vp = {}) { void host; return build(t, { ...params, data: params.data ?? clone(sample.data) }, vp); }, describe(t, params = {}, vp = {}) { return { sceneId: metaIn.id, t, params, vp, summary: metaIn.description }; }, sample() { return clone(sample); } });

export function makeStatBig(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const accent = params.color || WARM.accent; const data = chartOf(params.data, sample.data).slice(0, 4); const main = data[0]; const rest = data.slice(1, 4); const layers = [...base(W, H), box(W / 2, H * 0.45, W * 0.76, H * 0.44, WARM.panel, { opacity: 0.96, behaviors: [fadeIn(0, 0.5)] }), { shape: "circle", at: [W * 0.19, H * 0.25], radius: S * 0.035, fill: accent, opacity: 0.9, behaviors: [popIn(0.12, 0.45)] }, txt(W / 2, H * 0.31, main.label, S * 0.032, WARM.muted, { behaviors: [fadeIn(0.1, 0.5)] }), txt(W / 2, H * 0.46, `${main.value}${main.suffix}`, S * 0.13, WARM.text, { behaviors: [countUp(0.2, 1.1, { value: main.value }), slideInUp(0.12, 0.6, { distance: S * 0.04 })] })]; rest.forEach((item, i) => { const x = W * (0.25 + (i * 0.25)); const y = H * 0.73; const start = 0.45 + (i * 0.14); layers.push(box(x, y, W * 0.2, H * 0.16, WARM.card, { behaviors: [slideInUp(start, 0.6, { distance: 28 }), fadeIn(start, 0.45)] }), txt(x, y - H * 0.03, `${item.value}${item.suffix}`, S * 0.048, [accent, WARM.gold, WARM.sand][i], { behaviors: [countUp(start, 0.9, { value: item.value })] }), txt(x, y + H * 0.032, item.label, S * 0.023, WARM.muted, { behaviors: [fadeIn(start + 0.08, 0.45)] })); }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makeBarChart(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const accent = params.color || WARM.accent; const data = chartOf(params.data, sample.data).slice(0, 6); const max = Math.max(...data.map((d) => d.value), 1); const left = W * 0.14; const right = W * 0.9; const top = H * 0.2; const baseY = H * 0.77; const step = (right - left) / data.length; const bw = Math.min(step * 0.54, W * 0.09); const layers = [...base(W, H), txt(W * 0.22, H * 0.12, "Category Performance", S * 0.032, WARM.muted, { behaviors: [fadeIn(0, 0.5)] }), { shape: "rect", at: [(left + right) / 2, baseY], width: right - left, height: 3, fill: WARM.line, opacity: 0.8, behaviors: [chartReveal(0.1, 1.2, { data })] }, { shape: "rect", at: [left, (top + baseY) / 2], width: 3, height: baseY - top, fill: WARM.line, opacity: 0.8, behaviors: [chartReveal(0.1, 1.2, { data })] }]; data.forEach((item, i) => { const h = ((baseY - top) * item.value) / max; const x = left + (step * i) + (step / 2); const start = 0.28 + (i * 0.12); layers.push({ shape: "bar", at: [x, baseY - (h / 2)], width: bw, height: h, fill: [accent, WARM.gold, WARM.clay, WARM.sand][i % 4], tracks: { scaleY: [[start, 0.02], [start + 0.9, 1, "out"]] }, behaviors: [barGrow(start, 0.9, { percent: item.value }), fadeIn(start, 0.4)] }, txt(x, baseY + H * 0.06, item.label, S * 0.022, WARM.muted, { behaviors: [fadeIn(start + 0.05, 0.35)] }), txt(x, baseY - h - H * 0.04, `${item.value}${item.suffix}`, S * 0.024, WARM.text, { behaviors: [countUp(start + 0.1, 0.7, { value: item.value })] })); }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makeLineChart(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const accent = params.color || WARM.accent; const data = chartOf(params.data, sample.data).slice(0, 7); const max = Math.max(...data.map((d) => d.value), 1); const left = W * 0.13; const right = W * 0.88; const top = H * 0.2; const baseY = H * 0.76; const step = (right - left) / Math.max(1, data.length - 1); const points = data.map((item, i) => [left + (step * i), baseY - (((baseY - top) * item.value) / max)]); const layers = [...base(W, H), txt(W * 0.2, H * 0.12, "Signal Trend", S * 0.032, WARM.muted, { behaviors: [fadeIn(0, 0.5)] }), { shape: "rect", at: [(left + right) / 2, baseY], width: right - left, height: 3, fill: WARM.line, opacity: 0.75, behaviors: [chartReveal(0.1, 1.2, { data })] }, { shape: "rect", at: [left, (top + baseY) / 2], width: 3, height: baseY - top, fill: WARM.line, opacity: 0.75, behaviors: [chartReveal(0.1, 1.2, { data })] }, { shape: "line", at: [0, 0], points, stroke: accent, strokeWidth: Math.max(6, S * 0.01), opacity: 0.95, behaviors: [lineDraw(0.2, 1.2, { data })] }]; points.slice(1).forEach((point, i) => { layers.push({ shape: "line", at: [0, 0], points: [points[i], point], stroke: [accent, WARM.gold, WARM.sand][i % 3], strokeWidth: Math.max(5, S * 0.008), opacity: 0.9, behaviors: [fadeIn(0.28 + (i * 0.15), 0.35)] }); }); points.forEach((point, i) => { const start = 0.45 + (i * 0.12); layers.push({ shape: "circle", at: point, radius: Math.max(8, S * 0.012), fill: i === data.length - 1 ? WARM.gold : WARM.text, behaviors: [popIn(start, 0.45), nodeReveal(start, 0.45, { data: data.slice(0, i + 1) })] }, txt(point[0], baseY + H * 0.065, data[i].label, S * 0.021, WARM.muted, { behaviors: [fadeIn(start + 0.05, 0.3)] })); }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makePieChart(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const colors = [params.color || WARM.accent, WARM.gold, WARM.sand, WARM.clay]; const data = chartOf(params.data, sample.data).slice(0, 4); const total = Math.max(data.reduce((sum, item) => sum + Math.max(0, item.value), 0), 1); const cx = W * 0.33; const cy = H * 0.5; const radius = S * 0.2; let angle = 0; const layers = [...base(W, H), txt(W * 0.24, H * 0.12, "Audience Split", S * 0.032, WARM.muted, { behaviors: [fadeIn(0, 0.5)] }), { shape: "circle", at: [cx, cy], radius: radius + (S * 0.018), fill: WARM.card, opacity: 0.85, behaviors: [fadeIn(0.05, 0.5)] }]; data.forEach((item, i) => { const pct = (item.value / total) * 100; const start = 0.2 + (i * 0.18); layers.push({ shape: "pie", at: [cx, cy], value: pct, radius, rotate: angle, fill: colors[i % colors.length], behaviors: [pieFill(start, 0.9, { percent: pct }), popIn(start, 0.45)] }, txt(W * 0.7, H * (0.32 + (i * 0.11)), item.label, S * 0.024, WARM.text, { behaviors: [fadeIn(start + 0.1, 0.35)] }), txt(W * 0.84, H * (0.32 + (i * 0.11)), `${Math.round(pct)}%`, S * 0.026, colors[i % colors.length], { behaviors: [countUp(start + 0.12, 0.7, { value: Math.round(pct) })] })); angle += pct * 3.6; }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makeComparison(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const rows = compareOf(params.data, sample.data).slice(0, 3); const leftMax = Math.max(...rows.map((r) => r.left), 1); const rightMax = Math.max(...rows.map((r) => r.right), 1); const cols = [{ key: "left", title: "Before", x: W * 0.28, color: params.color || WARM.accent, max: leftMax }, { key: "right", title: "After", x: W * 0.72, color: WARM.gold, max: rightMax }]; const layers = [...base(W, H)]; cols.forEach((col, j) => { const start = 0.12 + (j * 0.15); const total = rows.reduce((sum, row) => sum + row[col.key], 0); layers.push(box(col.x, H * 0.48, W * 0.32, H * 0.56, WARM.panel, { behaviors: [slideInUp(start, 0.6, { distance: 32 }), fadeIn(start, 0.45)] }), txt(col.x, H * 0.18, col.title, S * 0.03, WARM.muted, { behaviors: [fadeIn(start, 0.4)] }), txt(col.x, H * 0.29, `${Math.round(total)}`, S * 0.082, col.color, { behaviors: [countUp(start + 0.08, 0.9, { value: Math.round(total) })] })); rows.forEach((row, i) => { const value = row[col.key]; const width = (W * 0.21 * value) / col.max; const y = H * (0.42 + (i * 0.13)); const rowStart = start + 0.18 + (i * 0.1); layers.push(txt(col.x, y - H * 0.045, row.label, S * 0.022, WARM.muted, { behaviors: [fadeIn(rowStart, 0.3)] }), { shape: "bar", at: [col.x - (W * 0.06), y], width, height: H * 0.042, fill: col.color, tracks: { scaleX: [[rowStart, 0.04], [rowStart + 0.7, 1, "out"]] }, behaviors: [barGrow(rowStart, 0.7, { percent: value }), fadeIn(rowStart, 0.25)] }, txt(col.x + W * 0.09, y, `${value}`, S * 0.025, WARM.text, { behaviors: [countUp(rowStart + 0.08, 0.6, { value })] })); }); }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makeProgressRing(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const accent = params.color || WARM.accent; const item = itemOf(dataOf(params.data, sample.data)[0], 0, sample.data[0].value); const target = clamp(item.value, 0, 100); const cx = W / 2; const cy = H * 0.5; const radius = S * 0.22; const layers = [...base(W, H), txt(cx, H * 0.16, item.label, S * 0.034, WARM.muted, { behaviors: [fadeIn(0.05, 0.5)] }), { shape: "ring", at: [cx, cy], radius, strokeWidth: S * 0.045, stroke: WARM.line, opacity: 0.7, behaviors: [fadeIn(0.08, 0.5)] }, { shape: "pie", at: [cx, cy], value: target, radius, fill: accent, behaviors: [pieFill(0.2, 1.1, { percent: target })] }, { shape: "circle", at: [cx, cy], radius: radius - (S * 0.06), fill: WARM.bg }, txt(cx, cy - S * 0.015, `${Math.round(target)}%`, S * 0.09, WARM.text, { behaviors: [countUp(0.25, 1.05, { value: Math.round(target) })] }), txt(cx, cy + S * 0.075, item.suffix || "completion", S * 0.022, WARM.muted, { behaviors: [fadeIn(0.42, 0.4)] })]; return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makeKpiGrid(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const data = chartOf(params.data, sample.data).slice(0, 4); const colors = [params.color || WARM.accent, WARM.gold, WARM.sand, WARM.clay]; const layers = [...base(W, H), txt(W * 0.2, H * 0.12, "KPI Snapshot", S * 0.032, WARM.muted, { behaviors: [fadeIn(0, 0.45)] })]; data.forEach((item, i) => { const col = i % 2; const row = Math.floor(i / 2); const x = W * (0.31 + (col * 0.38)); const y = H * (0.36 + (row * 0.28)); const start = 0.18 + (i * 0.12); layers.push(box(x, y, W * 0.28, H * 0.2, WARM.panel, { behaviors: [slideInUp(start, 0.55, { distance: 26 }), fadeIn(start, 0.4)] }), { shape: "rect", at: [x, y - H * 0.07], width: W * 0.28, height: H * 0.014, fill: colors[i], opacity: 0.9, behaviors: [fadeIn(start + 0.05, 0.3)] }, txt(x, y - H * 0.015, item.label, S * 0.024, WARM.muted, { behaviors: [fadeIn(start + 0.06, 0.35)] }), txt(x, y + H * 0.04, `${item.value}${item.suffix}`, S * 0.06, colors[i], { behaviors: [countUp(start + 0.1, 0.8, { value: item.value })] })); }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }
export function makeDataMap(metaIn, sample) { return withScene(metaIn, sample, (t, params, vp) => { void t; const [W, H, S] = vpOf(vp); const pins = dataOf(params.data, sample.data).slice(0, 5).map(pinOf); const layers = [...base(W, H), txt(W * 0.18, H * 0.12, "Global Distribution", S * 0.032, WARM.muted, { behaviors: [fadeIn(0, 0.45)] }), box(W / 2, H * 0.54, W * 0.82, H * 0.58, WARM.panel, { opacity: 0.92, behaviors: [fadeIn(0.05, 0.45)] })]; LANDS.forEach((points) => layers.push({ shape: "polygon", at: [W / 2, H * 0.54], points: points.map(([x, y]) => [x * (W / 1280), y * (H / 720)]), fill: "none", stroke: WARM.line, strokeWidth: Math.max(2, S * 0.0035), opacity: 0.9, behaviors: [chartReveal(0.12, 1.1, { data: pins })] })); pins.forEach((pin, i) => { const start = 0.3 + (i * 0.14); const x = W * (0.09 + (pin.x * 0.82)); const y = H * (0.25 + (pin.y * 0.46)); layers.push({ shape: "drop", at: [x, y], scale: 0.35, fill: i % 2 ? WARM.gold : (params.color || WARM.accent), behaviors: [mapPin(start, 0.75, { value: pin.value })] }, { shape: "circle", at: [x, y + S * 0.03], radius: S * 0.01, fill: WARM.sand, opacity: 0.85, behaviors: [fadeIn(start + 0.1, 0.25)] }, txt(x, y - S * 0.04, pin.label, S * 0.02, WARM.text, { behaviors: [fadeIn(start + 0.12, 0.35)] })); }); return { duration: metaIn.duration_hint, size: [W, H], layers }; }); }

export { meta };
